### ISSUE TITLE
Reticle

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#122]
## Story
It's super hard to tell where the player is placing a block. A reticle would help with this.

## MVP
What are the minimum features needed for this story?
-  [ ] On-screen reticle 

## Stretch
What are some non-required features for this story?
- [ ] Reticle color is configurable by Lua
- [ ] Reticle style is configurable by Lua
- [ ] Image can be set for reticle in Lua

**Comment by beeperdeeper089** [comment]
I'm assuming this means crosshair?

**Comment by apachano** [comment]
Yes

**Comment by beeperdeeper089** [comment]
I would think that maybe this being a Setting is a better idea. Lua shouldn't be registering a crosshair, since it should just be in the game imo, we should obviously provide full customisation, but a system like CS:GO's that has it inbuilt but fully customisable may make more sense. I'm open to suggestions, I'm still brainstorming how we can do this.

**Comment by tobyplowy** [comment]
Yeah I agree with @beeperdeeper089 here :)
